"""
Model Performance page — RMSE/MAE/R² comparison across all trained models,
stratified smog-vs-normal season evaluation, multi-horizon comparison, and
the SHAP summary plot. All four are generated by training_pipeline.py and
saved under reports/.
"""
import os
import pandas as pd
import streamlit as st
from PIL import Image

st.set_page_config(page_title="Model Performance · AQI Predictor", page_icon="📈", layout="wide")
st.title("📈 Model Performance & Explainability")


def _load_csv_or_warn(path: str, label: str):
    if os.path.exists(path):
        return pd.read_csv(path)
    st.info(f"`{path}` not found yet — generated by `training_pipeline.py` "
            f"after the daily training run. Run it once locally to populate {label}.")
    return None


st.subheader("Model comparison — 72h-ahead target (Persistence vs. all trained models)")
comparison_df = _load_csv_or_warn("reports/model_comparison.csv", "this table")
if comparison_df is not None:
    st.dataframe(comparison_df, use_container_width=True)
    best_row = comparison_df.iloc[0]
    st.caption(f"Best model: **{best_row['model']}** (RMSE={best_row['RMSE']:.2f}, "
               f"MAE={best_row['MAE']:.2f}, R²={best_row['R2']:.2f})")

st.divider()
st.subheader("Stratified evaluation — smog season vs. normal season")
strat_df = _load_csv_or_warn("reports/model_comparison_stratified.csv", "this table")
if strat_df is not None:
    st.dataframe(strat_df, use_container_width=True)
    st.caption(
        "Shows whether the winning model holds up during Lahore's Oct–Jan "
        "smog season specifically, rather than hiding behind one blended metric."
    )

st.divider()
st.subheader("Multi-horizon comparison — 24h / 48h / 72h ahead")
horizon_df = _load_csv_or_warn("reports/model_comparison_by_horizon.csv", "this table")
if horizon_df is not None:
    st.dataframe(horizon_df, use_container_width=True)
    st.line_chart(horizon_df.set_index("horizon_hours")[["RMSE", "MAE"]])
    st.caption("Expect RMSE/MAE to rise as the forecast horizon extends — "
               "normal behavior for forecasting models, worth noting in the report.")

st.divider()
st.subheader("SHAP feature importance (best tree-based model per horizon)")
shap_found = False
for horizon in (24, 48, 72):
    shap_path = f"reports/shap_summary_{horizon}h.png"
    if os.path.exists(shap_path):
        st.image(Image.open(shap_path), caption=f"SHAP summary — {horizon}h horizon")
        shap_found = True
if not shap_found:
    # Older training runs wrote a single shap_summary.png
    legacy = "reports/shap_summary.png"
    if os.path.exists(legacy):
        st.image(Image.open(legacy), caption="SHAP summary plot")
        shap_found = True
if not shap_found:
    st.info("SHAP summary plots not found yet — generated by training_pipeline.py "
            "after the daily training run (`reports/shap_summary_{24,48,72}h.png`).")
